### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Lahbak** [LABORA-INF-UFG/NetSoft2020-Tutorial4-Demo1-Exp1#1]
HI Team,
**When I put the command** 
root@ubuntu:~/project_1# cd NetSoft2020-Tutorial4-Demo1-Exp1 && ansible-playbook -K Demo1Exp1.yml
SUDO password: 
**I GOT THIS**
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

PLAY [127.0.0.1] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Environment validation!] *************************************************
ok: [127.0.0.1] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [Remove old instalation] **************************************************
 [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather
than running sudo

changed: [127.0.0.1]

TASK [Remove docker installation] **********************************************
skipping: [127.0.0.1]

TASK [Install Basic requirements] **********************************************
changed: [127.0.0.1]

TASK [Create dir instalation] **************************************************
changed: [127.0.0.1]

TASK [Add Docker GPG key into apt] *********************************************
changed: [127.0.0.1]

TASK [Add Docker APT repository] ***********************************************
changed: [127.0.0.1]

TASK [Update APT] **************************************************************
changed: [127.0.0.1]

TASK [Install Docker - CE] *****************************************************
changed: [127.0.0.1]

**TASK [Stop UE container - If exists] *******************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "docker stop -t 1 ue", "delta": "0:00:00.037240", "end": "2020-12-16 14:35:56.077849", "msg": "non-zero return code", "rc": 1, "start": "2020-12-16 14:35:56.040609", "stderr": "Error response from daemon: No such container: ue", "stderr_lines": ["Error response from daemon: No such container: ue"], "stdout": "", "stdout_lines": []}
...ignoring**

**TASK [Stop ENB container - If exists] ******************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "docker stop -t 1 enb", "delta": "0:00:00.036938", "end": "2020-12-16 14:35:56.243939", "msg": "non-zero return code", "rc": 1, "start": "2020-12-16 14:35:56.207001", "stderr": "Error response from daemon: No such container: enb", "stderr_lines": ["Error response from daemon: No such container: enb"], "stdout": "", "stdout_lines": []}
...ignoring**

TASK [Run doker prune in stoped containers] ************************************
changed: [127.0.0.1]

TASK [Remove enb-openairsim image] *********************************************
skipping: [127.0.0.1]

TASK [Remove ue-openairsim image] **********************************************
skipping: [127.0.0.1]

**TASK [Remove free5g docker custom network] *************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "docker network rm NetSoft2020Tutorial4", "delta": "0:00:00.041025", "end": "2020-12-16 14:35:56.635386", "msg": "non-zero return code", "rc": 1, "start": "2020-12-16 14:35:56.594361", "stderr": "Error: No such network: NetSoft2020Tutorial4", "stderr_lines": ["Error: No such network: NetSoft2020Tutorial4"], "stdout": "", "stdout_lines": []}
...ignoring**

TASK [Create Docker custom network] ********************************************
changed: [127.0.0.1]

TASK [Run OpenAirSIM-enB container] ********************************************

What shoud i do to resolve this problem ,please ?

**Comment by ciromacedo** [comment]
Hello Lahbak, how are you?
About the questions..

1º -  You must disregard the WARNING messages reported by Ansible. They happen due to the use of the default setting for the verbosity log level. You can disable add the line '**deprecation_warnings = False**' into  '**/etc/ansible/ansible.cfg**' config file, just below the '**[defaults]**' line.

2º - You should not worry about any tasks that may report an error message, but that end with the expression '**.... ignoring**'. These are expressions of errors duly expected during the deployment process. I built the playbook prepared to get around some possible scenarios, for example, if you run the playbook 2 times in a row on the same machine, the second execution will find the Docker installed and with the containers (**UE and ENB**) running correctly ? So it is necessary to check if they are already installed, if they are not installed '**.... ignoring**'.

Thanks for the feedback, any questions we are available!
